INSERT INTO product (name, desc, brand, price, category, release_date, available, quantity) VALUES
('Xplore Pen', 'Smooth writing pen', 'Xplore', 2.99, 'Stationery', CURRENT_DATE, true, 100),
('Adventure Notebook', 'Hardcover travel journal', 'Xplore', 12.50, 'Stationery', CURRENT_DATE, true, 50),
('Eco Bottle', 'Reusable water bottle', 'GreenLife', 8.75, 'Lifestyle', CURRENT_DATE, true, 75),
('Smart Lamp', 'Voice-controlled desk lamp', 'BrightTech', 29.99, 'Electronics', CURRENT_DATE, false, 0),
('Wireless Mouse', 'Ergonomic wireless mouse', 'ClickPro', 19.99, 'Electronics', CURRENT_DATE, true, 120),
('Bluetooth Speaker', 'Portable speaker with bass boost', 'SoundMax', 45.00, 'Electronics', CURRENT_DATE, true, 60),
('Desk Organizer', 'Multi-compartment desk tray', 'NeatSpace', 9.99, 'Office', CURRENT_DATE, true, 80),
('LED Strip Light', 'Color-changing LED strip', 'GlowTech', 14.99, 'Home Decor', CURRENT_DATE, true, 90),
('Fitness Band', 'Waterproof fitness tracker', 'FitPulse', 39.99, 'Wearables', CURRENT_DATE, true, 30),
('Noise Cancelling Headphones', 'Over-ear headphones with ANC', 'QuietZone', 89.99, 'Electronics', CURRENT_DATE, true, 25),
('Smart Watch', 'Touchscreen smartwatch with GPS', 'TimeX', 129.99, 'Wearables', CURRENT_DATE, true, 40),
('Laptop Stand', 'Adjustable aluminum stand', 'ErgoLift', 24.99, 'Office', CURRENT_DATE, true, 70),
('USB-C Hub', 'Multiport adapter with HDMI', 'Portify', 29.99, 'Electronics', CURRENT_DATE, true, 55),
('Travel Mug', 'Insulated stainless steel mug', 'SipMate', 17.50, 'Lifestyle', CURRENT_DATE, true, 100),
('Wireless Charger', 'Fast charging pad', 'ChargeUp', 22.00, 'Electronics', CURRENT_DATE, true, 65),
('Notebook Set', '3-pack ruled notebooks', 'PaperNest', 6.99, 'Stationery', CURRENT_DATE, true, 150),
('Mechanical Keyboard', 'RGB backlit keyboard', 'KeyForge', 59.99, 'Electronics', CURRENT_DATE, true, 35),
('Gaming Mousepad', 'Extended size with stitched edges', 'GameZone', 12.99, 'Gaming', CURRENT_DATE, true, 85),
('Smart Bulb', 'Wi-Fi enabled LED bulb', 'BrightTech', 11.99, 'Home Automation', CURRENT_DATE, true, 95),
('Cable Organizer', 'Magnetic cable clips', 'TidyTech', 5.99, 'Accessories', CURRENT_DATE, true, 200),
('Phone Stand', 'Adjustable desk phone holder', 'HoldIt', 8.99, 'Accessories', CURRENT_DATE, true, 110),
('Laptop Sleeve', 'Water-resistant 15-inch sleeve', 'SafeCarry', 18.99, 'Bags', CURRENT_DATE, true, 45),
('Wireless Earbuds', 'Bluetooth earbuds with mic', 'SoundMax', 49.99, 'Electronics', CURRENT_DATE, true, 60),
('Sticky Notes', 'Colorful sticky note pack', 'NoteIt', 3.49, 'Stationery', CURRENT_DATE, true, 300),
('Whiteboard Markers', 'Dry erase marker set', 'MarkPro', 7.99, 'Office', CURRENT_DATE, true, 90),
('Desk Lamp', 'LED lamp with USB port', 'BrightTech', 25.99, 'Office', CURRENT_DATE, true, 40),
('Fidget Spinner', 'Metal tri-spinner', 'SpinZone', 4.99, 'Toys', CURRENT_DATE, true, 150),
('Mini Tripod', 'Flexible phone tripod', 'SnapShot', 10.99, 'Photography', CURRENT_DATE, true, 70),
('Reusable Straw Set', 'Stainless steel straws', 'EcoSip', 6.50, 'Lifestyle', CURRENT_DATE, true, 130),
('Cable Ties', 'Velcro cable management', 'TidyTech', 4.99, 'Accessories', CURRENT_DATE, true, 180),
('Smart Plug', 'Wi-Fi smart outlet', 'PlugSmart', 16.99, 'Home Automation', CURRENT_DATE, true, 55),
('Notebook Cooler', 'USB-powered cooling pad', 'CoolBase', 21.99, 'Electronics', CURRENT_DATE, true, 50),
('Screen Cleaner Kit', 'Spray and microfiber cloth', 'ClearView', 9.50, 'Accessories', CURRENT_DATE, true, 100),
('Pen Holder', 'Mesh desk pen cup', 'NeatSpace', 3.99, 'Office', CURRENT_DATE, true, 140),
('Sticky Cable Clips', 'Adhesive cable holders', 'TidyTech', 5.49, 'Accessories', CURRENT_DATE, true, 160),
('LED Clock', 'Digital alarm clock with USB', 'TimeX', 18.75, 'Home Decor', CURRENT_DATE, true, 60),
('Portable Fan', 'USB mini desk fan', 'CoolBreeze', 13.99, 'Lifestyle', CURRENT_DATE, true, 75),
('Wireless Presenter', 'Laser pointer with USB receiver', 'SlidePro', 19.99, 'Office', CURRENT_DATE, true, 30),
('Laptop Backpack', 'Anti-theft tech backpack', 'SafeCarry', 39.99, 'Bags', CURRENT_DATE, true, 25),
('Bluetooth Keyboard', 'Slim wireless keyboard', 'KeyForge', 27.99, 'Electronics', CURRENT_DATE, true, 45),
('Drawing Tablet', 'USB graphic tablet', 'SketchMate', 59.99, 'Design', CURRENT_DATE, true, 20),
('LED Ring Light', 'Selfie light with tripod', 'GlowTech', 23.99, 'Photography', CURRENT_DATE, true, 35),
('Cable Sleeve', 'Neoprene cable management', 'TidyTech', 7.99, 'Accessories', CURRENT_DATE, true, 90),
('Smart Thermometer', 'Bluetooth body thermometer', 'MediTech', 14.99, 'Health', CURRENT_DATE, true, 40),
('Notebook Cooler Stand', 'Adjustable cooling stand', 'CoolBase', 26.99, 'Electronics', CURRENT_DATE, true, 30),
('USB Desk Fan', 'Quiet cooling fan', 'CoolBreeze', 11.99, 'Lifestyle', CURRENT_DATE, true, 80),
('Magnetic Whiteboard', 'Wall-mount dry erase board', 'NoteIt', 34.99, 'Office', CURRENT_DATE, true, 20),
('Ergonomic Chair Cushion', 'Memory foam seat pad', 'SitWell', 24.99, 'Office', CURRENT_DATE, true, 25),
('Smart Scale', 'Bluetooth body weight scale', 'FitPulse', 29.99, 'Health', CURRENT_DATE, true, 15),
('Wireless Charging Stand', 'Vertical fast charger', 'ChargeUp', 19.99, 'Electronics', CURRENT_DATE, true, 50);